### PR TITLE
Changes on humanpve1 layout for spacetracks

### PR DESCRIPTION
**Pull request by VReaperV**
-Moved trappers near h base to a better spot
-Moved an egg near alien default base, where aliens were getting stuck on spawn
-Replaced another egg in the same place with a hive
-Moved om off of the playable area
-Moved a couple more trappers to different places, to prevent them from being easily seen

### CODE REVIEW

**Comment by bmorel** [comment]
Does it now load? The "too many entities" thing is not very simple to fix, sadly.

**Comment by VReaperV** [comment]
It loads if it's done via /callvote layout. Changing map and layout at the same time (/devmap map layout and /callvote map layout) is what doesn't work,

**Comment by bmorel** [comment]
I didn't even knew it was possible to callvote layout! Thanks. If it loads with that, it's good enough for me.

BTW: cruz layout is hardcore with the nerfed flamer :D (but I intend to revert the nerf for my next version, with some other changes in AI). I had to go sleep before finishing tonight, at 3 a.m. (and was quite sleepy at work)

**Comment by VReaperV** [comment]
Oh yeah, it's probably the hardest layout I made, pretty easy to lose if you don't build anything in the beginning.

**Pull request merged**
